services:
  hcloud-dyndns:
    build: .
    container_name: hcloud-dyndns
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CONFIG=/config/hcloud-dyndns.conf
      - INTERVAL=300
      - MODE=loop
      - AUTO_CREATE=1
      # optional:
      # - SCRIPT_FLAGS=--verbose
      - SCRIPT_FLAGS=--quiet
    volumes:
      - ./config:/config:ro
